GET http://localhost:8080/api/employees/

###
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Valaki",
  "level": "Godlike",
  "position": "Joker",
  "brand":"64e4dffbeaa508fde173dc27"
}

###
DELETE http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779

###
// two types dinamic and condenser
PATCH http://localhost:8080/api/employees/63fc6e4bca1cb463caa21779
Content-Type:  application/json

{
  "name": "Jack Reacher",
  "level":"Medior",
  "position":"Superhero",
}


###
//Equipment database test
POST http://localhost:8080/api/equipment/
Content-Type: application/json

{
  "equipmentName": "Hero4 Camera",
  "type": "GoPro",
  "amount": 80
}


###
// Equipment test by id
PATCH http://localhost:8080/api/equipment/64e64705b7b09b79e839c12c
Content-Type:  application/json

{
  "equipmentName": "BodyArmor",
  "type":"West",
  "amount":15
}

//PA practice
###
GET http://localhost:8080/years-of-experience/2



//Own Practice
###
GET http://localhost:8080/same


###
PATCH http://localhost:8080/kittens/64ec8cd43e38ffaa1890700d
Content-Type:  application/json

{
"kittens":[
  {"name":"Mirci","weight":0.25},
  {"name":"Cirmike","weight":0.40},
  {"name":"Kormi","weight":0.30},
  {"name":"Tuluz","weight":0.45}
]
}

###
GET http://localhost:8080/api/position